### ISSUE TITLE
php 8.0 issue

### ISSUE THREAD

**Issue by tinchobug** [ycs77/laravel-form-builder-bs4#1]
Hi! I have error in update with php 8.0 composer update tried error
"Problem 1
    - ycs77/laravel-form-builder-bs4[v1.0.0, ..., v1.0.1] require php ~7.1 -> your php version (8.0.2) does not satisfy that requirement.
"

**Comment by ycs77** [comment]
Hello @tinchobug, fixed the bug with v1.0.2, can try again. 😄
